import { MaybeValue } from './value';
import { HTMLAttributes } from './html';

type Alignment = (
  'auto' |
  'baseline' |
  'before-edge' |
  'text-before-edge' |
  'middle' |
  'central' |
  'after-edge' |
  'text-after-edge' |
  'ideographic' |
  'alphabetic' |
  'hanging' |
  'mathematical' |
  'inherit'
);

type ArabicForm = 'initial' | 'medial' | 'terminal' | 'isolated';

type ColorInterpolationFilter = 'auto' | 'sRGB' | 'linearRGB' | 'inherit';

export interface SVGAttributes<Target extends EventTarget = SVGElement> extends HTMLAttributes<Target> {
  accentHeight?: MaybeValue<number | string | undefined>;
  accumulate?: MaybeValue<'none' | 'sum' | undefined>;
  additive?: MaybeValue<'replace' | 'sum' | undefined>;
  'alignment-baseline'?: MaybeValue<Alignment | undefined>;
  alphabetic?: MaybeValue<number | string | undefined>;
  amplitude?: MaybeValue<number | string | undefined>;
  /** @deprecated See https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/arabic-form */
  'arabic-form'?: MaybeValue<ArabicForm | undefined>;
  ascent?: MaybeValue<number | string | undefined>;
  attributeName?: MaybeValue<string | undefined>;
  /** @deprecated See https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/attributeType */
  attributeType?: MaybeValue<string | undefined>;
  azimuth?: MaybeValue<number | string | undefined>;
  baseFrequency?: MaybeValue<number | string | undefined>;
  'baseline-shift'?: MaybeValue<number | string | undefined>;
  baseProfile?: MaybeValue<number | string | undefined>;
  bbox?: MaybeValue<number | string | undefined>;
  begin?: MaybeValue<number | string | undefined>;
  bias?: MaybeValue<number | string | undefined>;
  by?: MaybeValue<number | string | undefined>;
  calcMode?: MaybeValue<number | string | undefined>;
  'cap-height'?: MaybeValue<number | string | undefined>;
  clip?: MaybeValue<number | string | undefined>;
  'clip-path'?: MaybeValue<string | undefined>;
  clipPathUnits?: MaybeValue<number | string | undefined>;
  'clip-rule'?: MaybeValue<number | string | undefined>;
  'color-interpolation'?: MaybeValue<number | string | undefined>;
  'color-interpolation-filters'?: MaybeValue<ColorInterpolationFilter | undefined>;
  'color-profile'?: MaybeValue<number | string | undefined>;
  'color-rendering'?: MaybeValue<number | string | undefined>;
  'content-script-type'?: MaybeValue<number | string | undefined>;
  'content-style-type'?: MaybeValue<number | string | undefined>;
  cursor?: MaybeValue<number | string | undefined>;
  cx?: MaybeValue<number | string | undefined>;
  cy?: MaybeValue<number | string | undefined>;
  d?: MaybeValue<string | undefined>;
  decelerate?: MaybeValue<number | string | undefined>;
  descent?: MaybeValue<number | string | undefined>;
  diffuseConstant?: MaybeValue<number | string | undefined>;
  direction?: MaybeValue<number | string | undefined>;
  display?: MaybeValue<number | string | undefined>;
  divisor?: MaybeValue<number | string | undefined>;
  'dominant-baseline'?: MaybeValue<number | string | undefined>;
  dur?: MaybeValue<number | string | undefined>;
  dx?: MaybeValue<number | string | undefined>;
  dy?: MaybeValue<number | string | undefined>;
  edgeMode?: MaybeValue<number | string | undefined>;
  elevation?: MaybeValue<number | string | undefined>;
  'enable-background'?: MaybeValue<number | string | undefined>;
  end?: MaybeValue<number | string | undefined>;
  exponent?: MaybeValue<number | string | undefined>;
  externalResourcesRequired?: MaybeValue<number | string | undefined>;
  fill?: MaybeValue<string | undefined>;
  'fill-opacity'?: MaybeValue<number | string | undefined>;
  'fill-rule'?: MaybeValue<'nonzero' | 'evenodd' | 'inherit' | undefined>;
  filter?: MaybeValue<string | undefined>;
  filterRes?: MaybeValue<number | string | undefined>;
  filterUnits?: MaybeValue<number | string | undefined>;
  'flood-color'?: MaybeValue<number | string | undefined>;
  'flood-opacity'?: MaybeValue<number | string | undefined>;
  focusable?: MaybeValue<number | string | undefined>;
  'font-family'?: MaybeValue<string | undefined>;
  'font-size'?: MaybeValue<number | string | undefined>;
  'font-size-adjust'?: MaybeValue<number | string | undefined>;
  'font-stretch'?: MaybeValue<number | string | undefined>;
  'font-style'?: MaybeValue<number | string | undefined>;
  'font-variant'?: MaybeValue<number | string | undefined>;
  'font-weight'?: MaybeValue<number | string | undefined>;
  format?: MaybeValue<number | string | undefined>;
  from?: MaybeValue<number | string | undefined>;
  fx?: MaybeValue<number | string | undefined>;
  fy?: MaybeValue<number | string | undefined>;
  g1?: MaybeValue<number | string | undefined>;
  g2?: MaybeValue<number | string | undefined>;
  'glyph-name'?: MaybeValue<number | string | undefined>;
  'glyph-orientation-horizontal'?: MaybeValue<number | string | undefined>;
  'glyph-orientation-vertical'?: MaybeValue<number | string | undefined>;
  glyphRef?: MaybeValue<number | string | undefined>;
  gradientTransform?: MaybeValue<string | undefined>;
  gradientUnits?: MaybeValue<string | undefined>;
  hanging?: MaybeValue<number | string | undefined>;
  height?: MaybeValue<number | string | undefined>;
  'horiz-adv-x'?: MaybeValue<number | string | undefined>;
  'horiz-origin-x'?: MaybeValue<number | string | undefined>;
  href?: MaybeValue<string | undefined>;
  hreflang?: MaybeValue<string | undefined>;
  ideographic?: MaybeValue<number | string | undefined>;
  'image-rendering'?: MaybeValue<number | string | undefined>;
  in2?: MaybeValue<number | string | undefined>;
  in?: MaybeValue<string | undefined>;
  intercept?: MaybeValue<number | string | undefined>;
  k1?: MaybeValue<number | string | undefined>;
  k2?: MaybeValue<number | string | undefined>;
  k3?: MaybeValue<number | string | undefined>;
  k4?: MaybeValue<number | string | undefined>;
  k?: MaybeValue<number | string | undefined>;
  kernelMatrix?: MaybeValue<number | string | undefined>;
  kernelUnitLength?: MaybeValue<number | string | undefined>;
  kerning?: MaybeValue<number | string | undefined>;
  keyPoints?: MaybeValue<number | string | undefined>;
  keySplines?: MaybeValue<number | string | undefined>;
  keyTimes?: MaybeValue<number | string | undefined>;
  lengthAdjust?: MaybeValue<number | string | undefined>;
  'letter-spacing'?: MaybeValue<number | string | undefined>;
  'lighting-color'?: MaybeValue<number | string | undefined>;
  limitingConeAngle?: MaybeValue<number | string | undefined>;
  local?: MaybeValue<number | string | undefined>;
  'marker-end'?: MaybeValue<string | undefined>;
  markerHeight?: MaybeValue<number | string | undefined>;
  'marker-mid'?: MaybeValue<string | undefined>;
  'marker-start'?: MaybeValue<string | undefined>;
  markerUnits?: MaybeValue<number | string | undefined>;
  markerWidth?: MaybeValue<number | string | undefined>;
  mask?: MaybeValue<string | undefined>;
  maskContentUnits?: MaybeValue<number | string | undefined>;
  maskUnits?: MaybeValue<number | string | undefined>;
  mathematical?: MaybeValue<number | string | undefined>;
  mode?: MaybeValue<number | string | undefined>;
  numOctaves?: MaybeValue<number | string | undefined>;
  offset?: MaybeValue<number | string | undefined>;
  opacity?: MaybeValue<number | string | undefined>;
  operator?: MaybeValue<number | string | undefined>;
  order?: MaybeValue<number | string | undefined>;
  orient?: MaybeValue<number | string | undefined>;
  orientation?: MaybeValue<number | string | undefined>;
  origin?: MaybeValue<number | string | undefined>;
  overflow?: MaybeValue<number | string | undefined>;
  'overline-position'?: MaybeValue<number | string | undefined>;
  'overline-thickness'?: MaybeValue<number | string | undefined>;
  'paint-order'?: MaybeValue<number | string | undefined>;
  /** @deprecatedhttps://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/panose-1 */
  'panose-1'?: MaybeValue<number | string | undefined>;
  pathLength?: MaybeValue<number | string | undefined>;
  patternContentUnits?: MaybeValue<string | undefined>;
  patternTransform?: MaybeValue<number | string | undefined>;
  patternUnits?: MaybeValue<string | undefined>;
  'pointer-events'?: MaybeValue<number | string | undefined>;
  points?: MaybeValue<string | undefined>;
  pointsAtX?: MaybeValue<number | string | undefined>;
  pointsAtY?: MaybeValue<number | string | undefined>;
  pointsAtZ?: MaybeValue<number | string | undefined>;
  preserveAlpha?: MaybeValue<number | string | undefined>;
  preserveAspectRatio?: MaybeValue<string | undefined>;
  primitiveUnits?: MaybeValue<number | string | undefined>;
  r?: MaybeValue<number | string | undefined>;
  radius?: MaybeValue<number | string | undefined>;
  refX?: MaybeValue<number | string | undefined>;
  refY?: MaybeValue<number | string | undefined>;
  'rendering-intent'?: MaybeValue<number | string | undefined>;
  'repeat-count'?: MaybeValue<number | string | undefined>;
  'repeat-dur'?: MaybeValue<number | string | undefined>;
  requiredExtensions?: MaybeValue<number | string | undefined>;
  requiredFeatures?: MaybeValue<number | string | undefined>;
  restart?: MaybeValue<number | string | undefined>;
  result?: MaybeValue<string | undefined>;
  rotate?: MaybeValue<number | string | undefined>;
  rx?: MaybeValue<number | string | undefined>;
  ry?: MaybeValue<number | string | undefined>;
  scale?: MaybeValue<number | string | undefined>;
  seed?: MaybeValue<number | string | undefined>;
  'shape-rendering'?: MaybeValue<number | string | undefined>;
  slope?: MaybeValue<number | string | undefined>;
  spacing?: MaybeValue<number | string | undefined>;
  specularConstant?: MaybeValue<number | string | undefined>;
  specularExponent?: MaybeValue<number | string | undefined>;
  speed?: MaybeValue<number | string | undefined>;
  spreadMethod?: MaybeValue<string | undefined>;
  startOffset?: MaybeValue<number | string | undefined>;
  stdDeviation?: MaybeValue<number | string | undefined>;
  stemh?: MaybeValue<number | string | undefined>;
  stemv?: MaybeValue<number | string | undefined>;
  stitchTiles?: MaybeValue<number | string | undefined>;
  'stop-color'?: MaybeValue<string | undefined>;
  'stop-opacity'?: MaybeValue<number | string | undefined>;
  'strikethrough-position'?: MaybeValue<number | string | undefined>;
  'strikethrough-thickness'?: MaybeValue<number | string | undefined>;
  string?: MaybeValue<number | string | undefined>;
  stroke?: MaybeValue<string | undefined>;
  'stroke-dasharray'?: MaybeValue<string | number | undefined>;
  'stroke-dashoffset'?: MaybeValue<string | number | undefined>;
  'stroke-linecap'?: MaybeValue<'butt' | 'round' | 'square' | 'inherit' | undefined>;
  'stroke-linejoin'?: MaybeValue<'miter' | 'round' | 'bevel' | 'inherit' | undefined>;
  'stroke-miterlimit'?: MaybeValue<string | number | undefined>;
  'stroke-opacity'?: MaybeValue<number | string | undefined>;
  'stroke-width'?: MaybeValue<number | string | undefined>;
  surfaceScale?: MaybeValue<number | string | undefined>;
  systemLanguage?: MaybeValue<number | string | undefined>;
  tableValues?: MaybeValue<number | string | undefined>;
  targetX?: MaybeValue<number | string | undefined>;
  targetY?: MaybeValue<number | string | undefined>;
  'text-anchor'?: MaybeValue<string | undefined>;
  'text-decoration'?: MaybeValue<number | string | undefined>;
  textLength?: MaybeValue<number | string | undefined>;
  'text-rendering'?: MaybeValue<number | string | undefined>;
  to?: MaybeValue<number | string | undefined>;
  transform?: MaybeValue<string | undefined>;
  'transform-origin'?: MaybeValue<string | undefined>;
  type?: MaybeValue<string | undefined>;
  u1?: MaybeValue<number | string | undefined>;
  u2?: MaybeValue<number | string | undefined>;
  'underline-position'?: MaybeValue<number | string | undefined>;
  'underline-thickness'?: MaybeValue<number | string | undefined>;
  unicode?: MaybeValue<number | string | undefined>;
  'unicode-bidi'?: MaybeValue<number | string | undefined>;
  'unicode-range'?: MaybeValue<number | string | undefined>;
  'units-per-em'?: MaybeValue<number | string | undefined>;
  'v-alphabetic'?: MaybeValue<number | string | undefined>;
  values?: MaybeValue<string | undefined>;
  'vector-effect'?: MaybeValue<number | string | undefined>;
  version?: MaybeValue<string | undefined>;
  'vert-adv-y'?: MaybeValue<number | string | undefined>;
  'vert-origin-x'?: MaybeValue<number | string | undefined>;
  'vert-origin-y'?: MaybeValue<number | string | undefined>;
  'v-hanging'?: MaybeValue<number | string | undefined>;
  'v-ideographic'?: MaybeValue<number | string | undefined>;
  viewBox?: MaybeValue<string | undefined>;
  viewTarget?: MaybeValue<number | string | undefined>;
  visibility?: MaybeValue<number | string | undefined>;
  'v-mathematical'?: MaybeValue<number | string | undefined>;
  width?: MaybeValue<number | string | undefined>;
  'word-spacing'?: MaybeValue<number | string | undefined>;
  'writing-mode'?: MaybeValue<number | string | undefined>;
  x1?: MaybeValue<number | string | undefined>;
  x2?: MaybeValue<number | string | undefined>;
  x?: MaybeValue<number | string | undefined>;
  xChannelSelector?: MaybeValue<string | undefined>;
  'x-height'?: MaybeValue<number | string | undefined>;
  'xlink:actuate'?: MaybeValue<string | undefined>;
  'xlink:arcrole'?: MaybeValue<string | undefined>;
  /** @deprecated See: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href */
  'xlink:href'?: MaybeValue<string | undefined>;
  'xlink:role'?: MaybeValue<string | undefined>;
  'xlink:show'?: MaybeValue<string | undefined>;
  'xlink:title'?: MaybeValue<string | undefined>;
  'xlink:type'?: MaybeValue<string | undefined>;
  'xml:base'?: MaybeValue<string | undefined>;
  'xml:lang'?: MaybeValue<string | undefined>;
  xmlns?: MaybeValue<string | undefined>;
  'xmlns:xlink'?: MaybeValue<string | undefined>;
  'xml:space'?: MaybeValue<string | undefined>;
  y1?: MaybeValue<number | string | undefined>;
  y2?: MaybeValue<number | string | undefined>;
  y?: MaybeValue<number | string | undefined>;
  yChannelSelector?: MaybeValue<string | undefined>;
  z?: MaybeValue<number | string | undefined>;
  zoomAndPan?: MaybeValue<string | undefined>;
}

export interface IntrinsicSVGElements {
  svg: SVGAttributes<SVGSVGElement>;
  animate: SVGAttributes<SVGAnimateElement>;
  circle: SVGAttributes<SVGCircleElement>;
  animateMotion: SVGAttributes<SVGAnimateMotionElement>;
  animateTransform: SVGAttributes<SVGAnimateTransformElement>;
  clipPath: SVGAttributes<SVGClipPathElement>;
  defs: SVGAttributes<SVGDefsElement>;
  desc: SVGAttributes<SVGDescElement>;
  ellipse: SVGAttributes<SVGEllipseElement>;
  feBlend: SVGAttributes<SVGFEBlendElement>;
  feColorMatrix: SVGAttributes<SVGFEColorMatrixElement>;
  feComponentTransfer: SVGAttributes<SVGFEComponentTransferElement>;
  feComposite: SVGAttributes<SVGFECompositeElement>;
  feConvolveMatrix: SVGAttributes<SVGFEConvolveMatrixElement>;
  feDiffuseLighting: SVGAttributes<SVGFEDiffuseLightingElement>;
  feDisplacementMap: SVGAttributes<SVGFEDisplacementMapElement>;
  feDistantLight: SVGAttributes<SVGFEDistantLightElement>;
  feDropShadow: SVGAttributes<SVGFEDropShadowElement>;
  feFlood: SVGAttributes<SVGFEFloodElement>;
  feFuncA: SVGAttributes<SVGFEFuncAElement>;
  feFuncB: SVGAttributes<SVGFEFuncBElement>;
  feFuncG: SVGAttributes<SVGFEFuncGElement>;
  feFuncR: SVGAttributes<SVGFEFuncRElement>;
  feGaussianBlur: SVGAttributes<SVGFEGaussianBlurElement>;
  feImage: SVGAttributes<SVGFEImageElement>;
  feMerge: SVGAttributes<SVGFEMergeElement>;
  feMergeNode: SVGAttributes<SVGFEMergeNodeElement>;
  feMorphology: SVGAttributes<SVGFEMorphologyElement>;
  feOffset: SVGAttributes<SVGFEOffsetElement>;
  fePointLight: SVGAttributes<SVGFEPointLightElement>;
  feSpecularLighting: SVGAttributes<SVGFESpecularLightingElement>;
  feSpotLight: SVGAttributes<SVGFESpotLightElement>;
  feTile: SVGAttributes<SVGFETileElement>;
  feTurbulence: SVGAttributes<SVGFETurbulenceElement>;
  filter: SVGAttributes<SVGFilterElement>;
  foreignObject: SVGAttributes<SVGForeignObjectElement>;
  g: SVGAttributes<SVGGElement>;
  image: SVGAttributes<SVGImageElement>;
  line: SVGAttributes<SVGLineElement>;
  linearGradient: SVGAttributes<SVGLinearGradientElement>;
  marker: SVGAttributes<SVGMarkerElement>;
  mask: SVGAttributes<SVGMaskElement>;
  metadata: SVGAttributes<SVGMetadataElement>;
  mpath: SVGAttributes<SVGMPathElement>;
  path: SVGAttributes<SVGPathElement>;
  pattern: SVGAttributes<SVGPatternElement>;
  polygon: SVGAttributes<SVGPolygonElement>;
  polyline: SVGAttributes<SVGPolylineElement>;
  radialGradient: SVGAttributes<SVGRadialGradientElement>;
  rect: SVGAttributes<SVGRectElement>;
  set: SVGAttributes<SVGSetElement>;
  stop: SVGAttributes<SVGStopElement>;
  switch: SVGAttributes<SVGSwitchElement>;
  symbol: SVGAttributes<SVGSymbolElement>;
  text: SVGAttributes<SVGTextElement>;
  textPath: SVGAttributes<SVGTextPathElement>;
  tspan: SVGAttributes<SVGTSpanElement>;
  use: SVGAttributes<SVGUseElement>;
  view: SVGAttributes<SVGViewElement>;
}
