import { WrapAttributes } from './util';
import { GenericAttributes } from './html';

type Alignment = (
  'auto' |
  'baseline' |
  'before-edge' |
  'text-before-edge' |
  'middle' |
  'central' |
  'after-edge' |
  'text-after-edge' |
  'ideographic' |
  'alphabetic' |
  'hanging' |
  'mathematical' |
  'inherit'
);

type ArabicForm = 'initial' | 'medial' | 'terminal' | 'isolated';

type ColorInterpolationFilter = 'auto' | 'sRGB' | 'linearRGB' | 'inherit';

export type SVGAttributes<Target extends EventTarget = SVGElement> = GenericAttributes<Target> & WrapAttributes<{
  accentHeight?: number | string;
  accumulate?: 'none' | 'sum';
  additive?: 'replace' | 'sum';
  'alignment-baseline'?: Alignment;
  alphabetic?: number | string;
  amplitude?: number | string;
  /** @deprecated See https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/arabic-form */
  'arabic-form'?: ArabicForm;
  ascent?: number | string;
  attributeName?: string;
  /** @deprecated See https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/attributeType */
  attributeType?: string;
  azimuth?: number | string;
  baseFrequency?: number | string;
  'baseline-shift'?: number | string;
  baseProfile?: number | string;
  bbox?: number | string;
  begin?: number | string;
  bias?: number | string;
  by?: number | string;
  calcMode?: number | string;
  'cap-height'?: number | string;
  clip?: number | string;
  'clip-path'?: string;
  clipPathUnits?: number | string;
  'clip-rule'?: number | string;
  'color-interpolation'?: number | string;
  'color-interpolation-filters'?: ColorInterpolationFilter;
  'color-profile'?: number | string;
  'color-rendering'?: number | string;
  'content-script-type'?: number | string;
  'content-style-type'?: number | string;
  cursor?: number | string;
  cx?: number | string;
  cy?: number | string;
  d?: string;
  decelerate?: number | string;
  descent?: number | string;
  diffuseConstant?: number | string;
  direction?: number | string;
  display?: number | string;
  divisor?: number | string;
  'dominant-baseline'?: number | string;
  dur?: number | string;
  dx?: number | string;
  dy?: number | string;
  edgeMode?: number | string;
  elevation?: number | string;
  'enable-background'?: number | string;
  end?: number | string;
  exponent?: number | string;
  externalResourcesRequired?: number | string;
  fill?: string;
  'fill-opacity'?: number | string;
  'fill-rule'?: 'nonzero' | 'evenodd' | 'inherit';
  filter?: string;
  filterRes?: number | string;
  filterUnits?: number | string;
  'flood-color'?: number | string;
  'flood-opacity'?: number | string;
  focusable?: number | string;
  'font-family'?: string;
  'font-size'?: number | string;
  'font-size-adjust'?: number | string;
  'font-stretch'?: number | string;
  'font-style'?: number | string;
  'font-variant'?: number | string;
  'font-weight'?: number | string;
  format?: number | string;
  from?: number | string;
  fx?: number | string;
  fy?: number | string;
  g1?: number | string;
  g2?: number | string;
  'glyph-name'?: number | string;
  'glyph-orientation-horizontal'?: number | string;
  'glyph-orientation-vertical'?: number | string;
  glyphRef?: number | string;
  gradientTransform?: string;
  gradientUnits?: string;
  hanging?: number | string;
  height?: number | string;
  'horiz-adv-x'?: number | string;
  'horiz-origin-x'?: number | string;
  href?: string;
  hreflang?: string;
  ideographic?: number | string;
  'image-rendering'?: number | string;
  in2?: number | string;
  in?: string;
  intercept?: number | string;
  k1?: number | string;
  k2?: number | string;
  k3?: number | string;
  k4?: number | string;
  k?: number | string;
  kernelMatrix?: number | string;
  kernelUnitLength?: number | string;
  kerning?: number | string;
  keyPoints?: number | string;
  keySplines?: number | string;
  keyTimes?: number | string;
  lengthAdjust?: number | string;
  'letter-spacing'?: number | string;
  'lighting-color'?: number | string;
  limitingConeAngle?: number | string;
  local?: number | string;
  'marker-end'?: string;
  markerHeight?: number | string;
  'marker-mid'?: string;
  'marker-start'?: string;
  markerUnits?: number | string;
  markerWidth?: number | string;
  mask?: string;
  maskContentUnits?: number | string;
  maskUnits?: number | string;
  mathematical?: number | string;
  mode?: number | string;
  numOctaves?: number | string;
  offset?: number | string;
  opacity?: number | string;
  operator?: number | string;
  order?: number | string;
  orient?: number | string;
  orientation?: number | string;
  origin?: number | string;
  overflow?: number | string;
  'overline-position'?: number | string;
  'overline-thickness'?: number | string;
  'paint-order'?: number | string;
  /** @deprecatedhttps://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/panose-1 */
  'panose-1'?: number | string;
  pathLength?: number | string;
  patternContentUnits?: string;
  patternTransform?: number | string;
  patternUnits?: string;
  'pointer-events'?: number | string;
  points?: string;
  pointsAtX?: number | string;
  pointsAtY?: number | string;
  pointsAtZ?: number | string;
  preserveAlpha?: number | string;
  preserveAspectRatio?: string;
  primitiveUnits?: number | string;
  r?: number | string;
  radius?: number | string;
  refX?: number | string;
  refY?: number | string;
  'rendering-intent'?: number | string;
  'repeat-count'?: number | string;
  'repeat-dur'?: number | string;
  requiredExtensions?: number | string;
  requiredFeatures?: number | string;
  restart?: number | string;
  result?: string;
  rotate?: number | string;
  rx?: number | string;
  ry?: number | string;
  scale?: number | string;
  seed?: number | string;
  'shape-rendering'?: number | string;
  slope?: number | string;
  spacing?: number | string;
  specularConstant?: number | string;
  specularExponent?: number | string;
  speed?: number | string;
  spreadMethod?: string;
  startOffset?: number | string;
  stdDeviation?: number | string;
  stemh?: number | string;
  stemv?: number | string;
  stitchTiles?: number | string;
  'stop-color'?: string;
  'stop-opacity'?: number | string;
  'strikethrough-position'?: number | string;
  'strikethrough-thickness'?: number | string;
  string?: number | string;
  stroke?: string;
  'stroke-dasharray'?: string | number;
  'stroke-dashoffset'?: string | number;
  'stroke-linecap'?: 'butt' | 'round' | 'square' | 'inherit';
  'stroke-linejoin'?: 'miter' | 'round' | 'bevel' | 'inherit';
  'stroke-miterlimit'?: string | number;
  'stroke-opacity'?: number | string;
  'stroke-width'?: number | string;
  surfaceScale?: number | string;
  systemLanguage?: number | string;
  tableValues?: number | string;
  targetX?: number | string;
  targetY?: number | string;
  'text-anchor'?: string;
  'text-decoration'?: number | string;
  textLength?: number | string;
  'text-rendering'?: number | string;
  to?: number | string;
  transform?: string;
  'transform-origin'?: string;
  type?: string;
  u1?: number | string;
  u2?: number | string;
  'underline-position'?: number | string;
  'underline-thickness'?: number | string;
  unicode?: number | string;
  'unicode-bidi'?: number | string;
  'unicode-range'?: number | string;
  'units-per-em'?: number | string;
  'v-alphabetic'?: number | string;
  values?: string;
  'vector-effect'?: number | string;
  version?: string;
  'vert-adv-y'?: number | string;
  'vert-origin-x'?: number | string;
  'vert-origin-y'?: number | string;
  'v-hanging'?: number | string;
  'v-ideographic'?: number | string;
  viewBox?: string;
  viewTarget?: number | string;
  visibility?: number | string;
  'v-mathematical'?: number | string;
  width?: number | string;
  'word-spacing'?: number | string;
  'writing-mode'?: number | string;
  x1?: number | string;
  x2?: number | string;
  x?: number | string;
  xChannelSelector?: string;
  'x-height'?: number | string;
  'xlink:actuate'?: string;
  'xlink:arcrole'?: string;
  /** @deprecated See: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href */
  'xlink:href'?: string;
  'xlink:role'?: string;
  'xlink:show'?: string;
  'xlink:title'?: string;
  'xlink:type'?: string;
  'xml:base'?: string;
  'xml:lang'?: string;
  xmlns?: string;
  'xmlns:xlink'?: string;
  'xml:space'?: string;
  y1?: number | string;
  y2?: number | string;
  y?: number | string;
  yChannelSelector?: string;
  z?: number | string;
  zoomAndPan?: string;
}>;

export interface IntrinsicSVGElements {
  svg: SVGAttributes<SVGSVGElement>;
  animate: SVGAttributes<SVGAnimateElement>;
  circle: SVGAttributes<SVGCircleElement>;
  animateMotion: SVGAttributes<SVGAnimateMotionElement>;
  animateTransform: SVGAttributes<SVGAnimateTransformElement>;
  clipPath: SVGAttributes<SVGClipPathElement>;
  defs: SVGAttributes<SVGDefsElement>;
  desc: SVGAttributes<SVGDescElement>;
  ellipse: SVGAttributes<SVGEllipseElement>;
  feBlend: SVGAttributes<SVGFEBlendElement>;
  feColorMatrix: SVGAttributes<SVGFEColorMatrixElement>;
  feComponentTransfer: SVGAttributes<SVGFEComponentTransferElement>;
  feComposite: SVGAttributes<SVGFECompositeElement>;
  feConvolveMatrix: SVGAttributes<SVGFEConvolveMatrixElement>;
  feDiffuseLighting: SVGAttributes<SVGFEDiffuseLightingElement>;
  feDisplacementMap: SVGAttributes<SVGFEDisplacementMapElement>;
  feDistantLight: SVGAttributes<SVGFEDistantLightElement>;
  feDropShadow: SVGAttributes<SVGFEDropShadowElement>;
  feFlood: SVGAttributes<SVGFEFloodElement>;
  feFuncA: SVGAttributes<SVGFEFuncAElement>;
  feFuncB: SVGAttributes<SVGFEFuncBElement>;
  feFuncG: SVGAttributes<SVGFEFuncGElement>;
  feFuncR: SVGAttributes<SVGFEFuncRElement>;
  feGaussianBlur: SVGAttributes<SVGFEGaussianBlurElement>;
  feImage: SVGAttributes<SVGFEImageElement>;
  feMerge: SVGAttributes<SVGFEMergeElement>;
  feMergeNode: SVGAttributes<SVGFEMergeNodeElement>;
  feMorphology: SVGAttributes<SVGFEMorphologyElement>;
  feOffset: SVGAttributes<SVGFEOffsetElement>;
  fePointLight: SVGAttributes<SVGFEPointLightElement>;
  feSpecularLighting: SVGAttributes<SVGFESpecularLightingElement>;
  feSpotLight: SVGAttributes<SVGFESpotLightElement>;
  feTile: SVGAttributes<SVGFETileElement>;
  feTurbulence: SVGAttributes<SVGFETurbulenceElement>;
  filter: SVGAttributes<SVGFilterElement>;
  foreignObject: SVGAttributes<SVGForeignObjectElement>;
  g: SVGAttributes<SVGGElement>;
  image: SVGAttributes<SVGImageElement>;
  line: SVGAttributes<SVGLineElement>;
  linearGradient: SVGAttributes<SVGLinearGradientElement>;
  marker: SVGAttributes<SVGMarkerElement>;
  mask: SVGAttributes<SVGMaskElement>;
  metadata: SVGAttributes<SVGMetadataElement>;
  mpath: SVGAttributes<SVGMPathElement>;
  path: SVGAttributes<SVGPathElement>;
  pattern: SVGAttributes<SVGPatternElement>;
  polygon: SVGAttributes<SVGPolygonElement>;
  polyline: SVGAttributes<SVGPolylineElement>;
  radialGradient: SVGAttributes<SVGRadialGradientElement>;
  rect: SVGAttributes<SVGRectElement>;
  set: SVGAttributes<SVGSetElement>;
  stop: SVGAttributes<SVGStopElement>;
  switch: SVGAttributes<SVGSwitchElement>;
  symbol: SVGAttributes<SVGSymbolElement>;
  text: SVGAttributes<SVGTextElement>;
  textPath: SVGAttributes<SVGTextPathElement>;
  tspan: SVGAttributes<SVGTSpanElement>;
  use: SVGAttributes<SVGUseElement>;
  view: SVGAttributes<SVGViewElement>;
}
